lib/resume_web/router.ex
defmodule ResumeWeb.Router do
  use ResumeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", ResumeWeb do
    pipe_through :browser

    get "/", CvController, :index
    get "/cvs/:lang/:version", CvController, :show
    get "/custom/:lang/:version/:template", CvController, :template
  end

  # Other scopes may use custom stacks.
  # scope "/api", ResumeWeb do
  #   pipe_through :api
  # end
end

lib/resume/cvs.ex
defmodule Resume.Cvs do

  def list do
    _configured_cvs()
  end
  
  def config(lang, version) do
    _yaml(lang, version, "config.yml")
  end
  def yaml(lang, version) do
    _yaml(lang, version, "cv.yml")
  end


  defp _configured_cvs do
    Path.wildcard("cvs/{de,en,fr,it}/**/config.yml") 
    |> Enum.map(&{&1, YamlElixir.read_from_file!(&1) |> _get_title_and_renderers()})
    |> Enum.reject(fn {_, {nil, _}} -> true; _ -> false end)
    |> Enum.map(&_extract_values/1)
  end

  defp _extract_lang_version(path) do
    path
    |> String.split("/")
    |> Enum.slice(1, 2)
  end

  defp _extract_values({path, {title, renderers}}) do
    [ lang, version ] = _extract_lang_version(path)
    %{lang: lang, version: version, title: title, renderers: renderers}
  end
  
  defp _get_title_and_renderers(config) do
    {Map.get(config, "title"), Map.get(config, "renderers") || []}
  end

  defp _yaml(lang, version, file) do
    YamlElixir.read_all_from_file!(Path.join(["cvs", lang, version, file]))
  end
end

lib/resume_web/controllers/cv_controller.ex
defmodule ResumeWeb.CvController do
  use ResumeWeb, :controller
  alias Resume.Cvs

  def index(conn, _params) do
    render(conn, "index.html", cvs: Cvs.list, title: "List of available CVs")
  end

  def show(conn, %{"lang" => lang, "version" => version, "renderer" => renderer}) do
    config = Cvs.config(lang, version) |> hd()
    name_for_title =
      config
      |> Map.get("name")
      |> String.replace(" ", "")

    yaml = Cvs.yaml(lang, version) |> hd()
    conn
    # |> put_layout(false)
    |> render("show.html", composer: Resume.Composer, cv: yaml, title: "CV-#{name_for_title}-#{lang}-#{version}", renderer: renderer )
    # |> render("#{renderer}/show.html", composer: Resume.Composer, cv: yaml, title: "CV-#{name_for_title}-#{lang}-#{version}", renderer: renderer )
  end

  def template(conn, %{"lang" => lang, "version" => version, "template" => template}) do
    yaml = Cvs.yaml(lang, version) |> hd()
    conn
    |> render("#{template}.html", composer: Resume.Composer, cv: yaml )
  end

  
end

lib/resume_web/views/cv_view.ex
defmodule ResumeWeb.CvView do
  use ResumeWeb, :view
end

lib/resume_web/templates/cv/index.html.eex
<h2>Available CVs</h2>

<section class="container">

  <table>
    <thead>
      <tr>
      <th>Title</th>
      <th>Version</th>
      <th>Lang</th>
      <th>Show</th>
      </tr>
    </thead>
    <tbody>
      <%= for cv <- @cvs do %>
        <tr>
          <td>
            <%= cv.title %>
          </td>
          <td>
            <%= cv.version %> 
          </td>
          <td>
            <%= cv.lang %>
          </td>
          <% renderers = Map.get(cv, :renderers) %>
          <%= for renderer <- renderers do %>
            <td>
              <%= link renderer, to: Routes.cv_path(@conn, :show, cv.lang, cv.version, renderer: renderer) %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

lib/resume_web/templates/cv/show.html.eex
<div id="info">
  <pre><code>
    CV: <%= @title %>
    Renderer: <%= @renderer %>
  </code></pre>
</div>
  <%= render("#{@renderer}/show.html", composer: Resume.Composer, cv: @cv, title: @title, renderer: @renderer ) %>